name: Test the environment

on: 
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'Environment'
        required: true
        options:
          - "dev"
          - "qa"
          - "prod"

jobs:
  create_rscs:
    name: Create resources
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    env:
      # ARM_CLIENT_ID: ${{ secrets.TF_VAR_AGENT_CLIENT_ID }}
      # ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_AGENT_CLIENT_SECRET }}
      # ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
      # ARM_TENANT_ID: ${{ secrets.TF_VAR_TENANT_ID }}

      RG_NAME: ${{ secrets.RG_NAME }}
      STGACC_NAME: ${{ secrets.STG_ACC }}
      ENV_NAME: ${{ github.event.inputs.env }}

      # GC_PROJECT_ID: ${{ secrets.GC_PROJECT_ID }}
      # GC_LOCATION: ${{ secrets.GC_LOCATION }}
      # GC_BUCKET_NAME: smgc-${{ github.event.inputs.env }}-docai-cs-tfstatefile

    steps:
      - name: "Print out the environment variable"
        run: |        
          #az storage account list --output tsv | grep $stgAccount -q || az storage account create -n $stgAccount -g $rgName -l eastus --sku Standard_LRS
          #  echo ${{secrets.SECRET_NAME}} | sed 's/./& /g'
          # mkdir $RG_NAME
          # mkdir $STGACC_NAME
          
          echo ${{secrets.RG_NAME}} | sed 's/./& /g'
          echo ${{secrets.STGACC_NAME}} | sed 's/./& /g'
          
          echo $ENV_NAME
          ls -atl .

