name: Test the environment

on: 
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'Environment'
        required: true
        options:
          - "dev"
          - "qa"
          - "prod"

jobs:
  create_rscs:
    name: Create resources on  ${{ github.event.inputs.env }} env
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    env:
      # ARM_CLIENT_ID: ${{ secrets.TF_VAR_AGENT_CLIENT_ID }}
      # ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_AGENT_CLIENT_SECRET }}
      # ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
      # ARM_TENANT_ID: ${{ secrets.TF_VAR_TENANT_ID }}

      RG_NAME: ${{ secrets.RG_NAME }}
      STGACC_NAME: ${{ secrets.STG_ACC }}
      ENV_NAME: ${{ github.event.inputs.env }}

      # GC_PROJECT_ID: ${{ secrets.GC_PROJECT_ID }}
      # GC_LOCATION: ${{ secrets.GC_LOCATION }}
      # GC_BUCKET_NAME: smgc-${{ github.event.inputs.env }}-docai-cs-tfstatefile

      #GCP_FUNCTIONAPP_NAME: smgc-${{ github.event.inputs.env }}-docai-cf-sis
      #GCP_FUNCTIONAPP_ENTRYPOINT: com.sproutmortgage.docai.function.SplitInformationSender
      GCP_FUNCTIONAPP_NAME: function-test-documentai
      GCP_FUNCTIONAPP_ENTRYPOINT: com.example.Example
      #GCP_FUNCTIONAPP_EVENT_RESOURCE: projects/ardent-oven-240715/buckets/smgc-${{ github.event.inputs.env }}-docai-cs-lendingai
      GCP_FUNCTIONAPP_EVENT_RESOURCE: projects/ardent-oven-240715/buckets/smgc-devops-document1-cs-lendingai
      GCP_FUNCTIONAPP_EVENT_TYPE: google.storage.object.finalize
      GCP_REGION: us-east1
      GCP_PROJECT_ID: ardent-oven-240715
      GCP_SERVICE_ACCOUNT_EMAIL: dev-svc-infra@ardent-oven-240715.iam.gserviceaccount.com



    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
        
      - name: "Print out the environment variable"
        run: |        
          #az storage account list --output tsv | grep $stgAccount -q || az storage account create -n $stgAccount -g $rgName -l eastus --sku Standard_LRS
          #  echo ${{secrets.SECRET_NAME}} | sed 's/./& /g'
          # mkdir $RG_NAME
          # mkdir $STGACC_NAME
          
          echo $RG_NAME | sed 's/./& /g'

          echo $STGACC_NAME | sed 's/./& /g'
          
          echo $ENV_NAME
          ls -atl .

      - name: Google Cloud Authentication
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Google Cloud
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: '${{ env.GCP_FUNCTIONAPP_NAME }}'
          service_account_email: '${{ env.GCP_SERVICE_ACCOUNT_EMAIL }}'
          runtime: 'java11'
          entry_point: '${{ env.GCP_FUNCTIONAPP_ENTRYPOINT }}'
          region: '${{ env.GCP_REGION }}'
          event_trigger_type: '${{ env.GCP_FUNCTIONAPP_EVENT_TYPE }}'
          project_id: '${{ env.GCP_PROJECT_ID }}'
          event_trigger_resource: '${{ env.GCP_FUNCTIONAPP_EVENT_RESOURCE }}'
          event_trigger_retry: true
          source_dir: './dist'